#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
. ${fhome}/func_debug_Setting_$DebugLev
#
JobStartTime=`date`; echo ${Line_Break}; echo ${Line_Break}
JobName=func_gp2sp
# 
echo "Starting "${JobName}" ...... "
#tempPrefix=t_'gp2sp_'$$
###############################################################################
SupportData=${scripthome}/${supported_models}/${Model}
cd ${DataIngestionCommPool}/../Data/${Model}/
rm -f t_gp2sp_*
${CDO} -f nc copy -selvar,t,u,v ${data_vi} ${tempPrefix}_CL_TUV
${CDO} -f nc copy -selvar,sp ${data_vi} ${tempPrefix}_CL_PS
cp -f ${tempPrefix}_CL_PS ${DIData}/${Model}/data_${Model}_sp
#${CDO} -delete,name=t,u,v ${data_vi} ${data_vi}_CL_no_tuv
${CDO} -ln ${tempPrefix}_CL_PS ${tempPrefix}_CL_lsp
#${CDO} -merge ${tempPrefix}_CL_lsp ${tempPrefix}_CL_TUV ${tempPrefix}_CL_merged 
${CDO} -gp2sp -uv2dv -remapcon,t${Csp_res}grid ${tempPrefix}_CL_TUV ${tempPrefix}_CL_sp_${Csp_res}
${CDO} -gp2sp -remapcon,t${Csp_res}grid ${tempPrefix}_CL_lsp ${tempPrefix}_CL_lsp_CL_sp_${Csp_res}

if [ ${S0sp_res} -ge 0 ]; then
  ${CDO} -sp2sp,${Ssp_res} -sp2sp,${S0sp_res} ${tempPrefix}_CL_sp_${Csp_res} ${tempPrefix}_CL_sp_${S0sp_res}
fi
${CDO} -sp2sp,${Ssp_res} ${tempPrefix}_CL_sp_${Csp_res} ${tempPrefix}_CL_sp_${Ssp_res}
if [ ${S0sp_res} -ge 0 ]; then
  ${CDO} -sub ${tempPrefix}_CL_sp_${Ssp_res} ${tempPrefix}_CL_sp_${S0sp_res} ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}
else
  ln -sf ${tempPrefix}_CL_sp_${Ssp_res} ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}
fi
${CDO} -sp2sp,${Csp_res} ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res} ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}to${Csp_res}_nolsp
${CDO} -merge ${tempPrefix}_CL_lsp_CL_sp_${Csp_res} ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}to${Csp_res}_nolsp ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}to${Csp_res}


mv ${tempPrefix}_CL_sp_${S0sp_res}-${Ssp_res}to${Csp_res} ${data_vi}_visp

###############################################################################
echo `date`" || "${JobName}
echo ${Line_Break}
