#! /bin/bash
###############################################################################
# 
#------------------------------------------------------------------------------
#
JobStartTime=`date`; echo ${Line_Break}; echo ${Line_Break}
JobName=func_DI_sync_fetched 
# 
echo "Starting "${JobName}" ...... "
###############################################################################
# Implementing this in order to sync sync-monitoring part and model monitoring part 
is_DI_fetched=${FlagsDir}/DI_fetched_$$$$

echo "fetched ..." > ${is_DI_fetched}

while [ -f ${is_DI_fetched} ]; do
  is_all_data_fetched=1
  for Model in ${Models}; do
    is_ModelData_fetched=${FlagsDir}/MD_${Model}_is_fetched
    Model_DI_Data=${DIData}/${Model}/DI_Data_${yy}${mm}${dd}_${ss}.nc
    if [ -f ${Model_DI_Data} ] && [ ! -f ${is_ModelData_fetched} ] ; then
      is_all_data_fetched=0
    else
      echo "1" > ${is_ModelData_fetched} 
    fi
  done
  if [ "${is_all_data_fetched}" == "1" ]; then
    rm ${is_DI_fetched}; rm -f ${FlagsDir}/MD_*_is_fetched
  fi
  sleep ${sleepS}s
done

###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${Line_Break}
