#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
envConfigFilePath=functions/DIM_${DI_Method}; . ${fhome}/func_getenvxmlValue
Ssp_res=`func_getenvxmlValue "//model-parameters[@name=\"Basic\"]/param" "Selected spherical harmonics"`
Csp_res=`func_getenvxmlValue "//model-parameters[@name=\"Basic\"]/param" "Common spherical harmonics"`
envConfigFilePath=functions; . ${fhome}/func_getenvxmlValue



. ${fhome}/func_debug_Setting_$DebugLev
cd ${DataIngestionCommPool}/../Data/${Model}
mv ${DIData}/${Model}/work/${tempPrefix}_ML_sync ${tempPrefix}_ML_sync_gp_S${Ssp_res}

data_org=${DataIngestionCommPool}/../Data/${Model}/data_${Model}_org_${yy}-${mm}-${dd}-${ss}

${CDO} -selvar,T,U,V,PS,Q ${data_org} ${tempPrefix}_ML_TUVQPS
#${CDO} -selvar,PS ${data_vi} ${tempPrefix}_PS
${CDO} -delete,name=T,U,V,PS,Q ${data_org} ${tempPrefix}_ML_no_TUVQPS
#${CDO} -ln ${tempPrefix}_PS ${tempPrefix}_lsp
#${CDO} -merge ${tempPrefix}_lsp ${tempPrefix}_TUV ${tempPrefix}_merged
${CDO} -sp2sp,${Ssp_res} -gp2sp -uv2dv -remapcon,t${Csp_res}grid ${tempPrefix}_ML_TUVQPS ${tempPrefix}_ML_sp_S${Ssp_res}
#${CDO} -sp2sp,${CN_res} ${tempPrefix}_ML_sp_${SN_RES} ${tempPrefix}_ML_sp_${CN_res}
${CDO} -remapcon,${SupportData}/Model_griddes.txt -sp2gp -dv2uv -sp2sp,${Csp_res} ${tempPrefix}_ML_sp_S${Ssp_res} ${tempPrefix}_ML_gp_S${Ssp_res}
${CDO} -sub ${tempPrefix}_ML_TUVQPS ${tempPrefix}_ML_gp_S${Ssp_res} ${tempPrefix}_ML_gp_TUVQPS_res


${CDO} -selvar,T,U,V,PS,Q ${tempPrefix}_ML_sync_gp_S${Ssp_res} ${tempPrefix}_ML_sync_TUVQPS
${CDO} -sp2sp,${Ssp_res} -gp2sp -uv2dv -remapcon,t${Csp_res}grid ${tempPrefix}_ML_sync_TUVQPS ${tempPrefix}_ML_sync_sp_S${Ssp_res}
${CDO} -remapcon,${SupportData}/Model_griddes.txt -sp2gp -dv2uv -sp2sp,${Csp_res} ${tempPrefix}_ML_sync_sp_S${Ssp_res} ${tempPrefix}_ML_sync_gp_S${Ssp_res}uv
${CDO} -chname,u,U,v,V ${tempPrefix}_ML_sync_gp_S${Ssp_res}uv ${tempPrefix}_ML_sync_gp_S${Ssp_res}
${CDO} -enssum ${tempPrefix}_ML_sync_gp_S${Ssp_res} ${tempPrefix}_ML_gp_TUVQPS_res ${tempPrefix}_ML_sync_merged

${CDO} -merge ${tempPrefix}_ML_sync_merged ${tempPrefix}_ML_no_TUVQPS ${tempPrefix}_gp2sp2gp

rm -f ${data_org}
###############################################################################
echo ${Line_Break}
