#! /bin/bash
###############################################################################
# ensemble info
#------------------------------------------------------------------------------
. ${fhome}/func_debug_Setting_$DebugLev
#
JobStartTime=`date`; echo ${Line_Break}; echo ${Line_Break}
JobName=func_gp2sp
# 
echo "Starting "${JobName}" ...... "
#tempPrefix=t_'gp2sp_'$$
###############################################################################
envConfigFilePath=functions/DIM_${DI_Method}; . ${fhome}/func_getenvxmlValue
Ssp_res=`func_getenvxmlValue "//model-parameters[@name=\"Basic\"]/param" "Selected spherical harmonics"`
Csp_res=`func_getenvxmlValue "//model-parameters[@name=\"Basic\"]/param" "Common spherical harmonics"`
echo $Ssp_res $Csp_res
envConfigFilePath=functions; . ${fhome}/func_getenvxmlValue

SupportData=${scripthome}/${supported_models}/${Model}
cd ${DataIngestionCommPool}/../Data/${Model}/
rm -f t_gp2sp_*
${CDO} -f nc copy -selvar,t,u,v ${data_vi} ${tempPrefix}_CL_TUV
${CDO} -f nc copy -selvar,sp ${data_vi} ${tempPrefix}_CL_PS
#${CDO} -delete,name=t,u,v ${data_vi} ${data_vi}_CL_no_tuv
${CDO} -ln ${tempPrefix}_CL_PS ${tempPrefix}_CL_lsp
${CDO} -merge ${tempPrefix}_CL_lsp ${tempPrefix}_CL_TUV ${tempPrefix}_CL_merged 
${CDO} -gp2sp -uv2dv -remapcon,t${Csp_res}grid ${tempPrefix}_CL_merged ${tempPrefix}_CL_sp_C${Csp_res}
${CDO} -sp2sp,${Ssp_res} ${tempPrefix}_CL_sp_C${Csp_res} ${tempPrefix}_CL_sp_S${Ssp_res}

# get residural 
#time ${CDO} -remapcon,${SupportData}/Model_griddes.txt -sp2gp -dv2uv ${tempPrefix}_sp_${SN_RES} ${tempPrefix}_sp2gp
#MS ${CDO} -sub ${tempPrefix}_sp_${CN_res} ${tempPrefix}_sp_${SN_RES}to${CN_res} ${tempPrefix}_sp_res  

#MS mv ${tempPrefix}_sp_res ${data_vi}_visp_res  

#cp ${tempPrefix}_CL_sp_${SN_RES} ${data_vi}_visp 

###############################################################################
echo `date`" || "${JobName}
echo ${Line_Break}
