#! /bin/bash
###############################################################################
. ${fhome}/func_debug_Setting_${DebugLev}
JobStartTime=`date`; echo ${Line_Break}; echo ${Line_Break}
JobName=func_demo_DI_preparing 
echo "Starting "${JobName}" ...... "
###############################################################################



whileControlFlag=${FlagsDir}/${tempPrefix}_${JobName}_Flag_$$$$
echo "1" > ${whileControlFlag}
Counter=0; MaxSleepCounter=1
while [ ! -f ${file2check} -a ${Counter} -lt ${MaxSleepCounter} -a -f ${whileControlFlag} ]; do
  echo "${Model}: wait for data ... ${file2check} ..."
  sleep ${sleepS}s
  SourceDataWaitingCounter=`echo "scale=0;(${SourceDataWaitingCounter}+1)" | bc -l `
done
rm ${whileControlFlag}
###############################################################################
echo ${JobStartTime}
echo `date`" || "${JobName}
echo ${Line_Break}
