#! /bin/bash
if [ "${is_rebuild_Model}" == "TRUE" ]; then
  cd /cluster/projects/nn9385k/people/agu002/ERC-STERCP/models/noresm1-me/scripts #MSNU#

  [ ! -z ${Model_script_dir} ] && [ -d ${Model_script_dir} ] && rm -rf ${Model_script_dir}
  if [ "${model_type}" == "couple" ]; then
    # NorESM1 compset
    ./create_newcase -case ${Model_script_dir} -compset N20TREXTAERCN -res f19_g16 -mach ${HPC} -pecount=X1
  elif [ "${model_type}" == "AMIP" ]; then
    # CAM4 compset
    ./create_newcase -case ${Model_script_dir} -compset F -res f19_f19 -mach ${HPC} -pecount=L
  elif [ "${model_type}" == "OMIP" ]; then
    # BLOM compset
    echo "not implement yet "
  fi

  ty=${yy};tm=${mm};td=${dd};
  DateTime=${Model_ref_date}-00000; . ${fhome}/func_split_datetime
  Ry=${yy};Rm=${mm};Rd=${dd};yy=${ty};mm=${tm};dd=${td};

  cd ${Model_script_dir}
  ./xmlchange -file env_run.xml -id LOGDIR -val ${Model_work_dir}/../logs
  ./xmlchange -file env_run.xml -id STOP_OPTION -val nmonths
  ./xmlchange -file env_run.xml -id STOP_N -val ${ModelIntegrationCycle}
  ./xmlchange -file env_run.xml -id RESUBMIT -val 0
  ./xmlchange -file env_run.xml -id RESTART -val 0
  ./xmlchange -file env_run.xml -id DIN_LOC_ROOT_CSMDATA -val /cluster/shared/noresm/inputdata
  org_CAM_CONFIG_OPTS=`grep CAM_CONFIG_OPTS  env_conf.xml | awk -F "value=\"" '{print $2}' | awk -F "\" " '{print  $1}'`
  is_OfflineDyn_defined=`echo ${org_CAM_CONFIG_OPTS} | grep offline_dyn` || is_OfflineDyn_defined="False"
  if [ "${is_OfflineDyn_defined}" == "False" ]; then
    new_CAM_CONFIG_OPTS=${org_CAM_CONFIG_OPTS}" -offline_dyn -scen_rcp rcp85 "
  else
    new_CAM_CONFIG_OPTS=${org_CAM_CONFIG_OPTS}
  fi
  ./xmlchange -file env_conf.xml -id CAM_CONFIG_OPTS -val "${new_CAM_CONFIG_OPTS}"
  ./xmlchange -file env_build.xml -id EXEROOT -val ${Model_work_dir}/../
  ./xmlchange -file env_run.xml -id DOUT_S_ROOT -val ${Model_work_dir}/../../archive/\${CASE}
  DateTime=${Date_time_ini}; . ${fhome}/func_split_datetime
  ./xmlchange -file env_conf.xml -id RUN_STARTDATE -val ${yy}-${mm}-${dd}
  ./xmlchange -file env_conf.xml -id RUN_REFDATE -val ${Ry}-${Rm}-${Rd}
  ./xmlchange -file env_run.xml -id CONTINUE_RUN -val ${is_ContinueRun}
  ./xmlchange -file env_conf.xml -id RUN_TYPE -val ${run_type}
  ./xmlchange -file env_conf.xml -id RUN_REFCASE -val ${Model_ref_case}
 
  if [ "${model_type}" == "AMIP" ] || [ ${Model_CPU_req} -le 128 ]; then
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ATM -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id NTASKS_LND -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id NTASKS_ICE -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id NTASKS_OCN -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id NTASKS_CPL -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id NTASKS_GLC -val ${Model_CPU_req}
    ./xmlchange -file env_mach_pes.xml -id TOTALPES -val ${Model_CPU_req}
  fi
  if [ ${Model_CPU_req} -le 128 ]; then
    ./xmlchange -file env_mach_pes.xml -id ROOTPE_ATM -val 0
    ./xmlchange -file env_mach_pes.xml -id ROOTPE_LND -val 0
    ./xmlchange -file env_mach_pes.xml -id ROOTPE_ICE -val 0
    ./xmlchange -file env_mach_pes.xml -id ROOTPE_OCN -val 0
    ./xmlchange -file env_mach_pes.xml -id ROOTPE_CPL -val 0
  fi

  ./configure -case

  if [ "${run_type}" == "brabch" ]; then
    sed -i s/"start_ymd".*/"start_ymd  = ${yy}${mm}${dd}"/g Buildconf/cpl.buildnml.csh
  fi

  # keep HPC configuration in case of performing individual test
  if [ "${HPC}" == "hexagon" ]; then
    sed -i s/"PBS -N ".*/"PBS -N r_${CaseName}"/g  ${CaseName}.*.run
    sed -i s/"PBS -A ".*/"PBS -A ${CPUACCOUNT}"/g  ${CaseName}.*.run
    sed -i s/"PBS -l walltime".*/"PBS -l walltime=00:59:00"/g ${CaseName}.*.run
    sed -i s/"FC            :=".*/"FC         :=  time ftn -traceback "/g Macros.${HPC}
  elif [ "${HPC}" == "fram" ]; then
    #sed -i s/"#SBATCH --job-name=".*/"#SBATCH --job-name=r_${CaseName}"/g  ${CaseName}.*.run
    sed -i s/"#SBATCH --error=".*/"#SBATCH --error=r_${CaseName}_err"/g  ${CaseName}.*.run
    sed -i s/"#SBATCH --output=".*/"#SBATCH --output=r_${CaseName}_out"/g  ${CaseName}.*.run
    sed -i s/"#SBATCH --account=".*/"#SBATCH --account=${CPUACCOUNT}"/g  ${CaseName}.*.run
    sed -i s/"#SBATCH --time=".*/"#SBATCH --time=00:59:00"/g ${CaseName}.*.run
    sed -i s/"FC            :=".*/"FC         :=  time mpiifort -traceback "/g Macros.${HPC}
  fi

  if [ "${model_type}" == "couple" ]; then
    # NorESM1
    sed -i s/"IDATE    =".*/"IDATE    = ${yy}${mm}${dd},"/g Buildconf/micom.buildnml.csh
    sed -i s/"IDATE0   =".*/"IDATE0   = ${yy}${mm}${dd},"/g Buildconf/micom.buildnml.csh
  fi

  # update SLURM environments
  sed -i s/"export SLURM_MEM_PER_CPU".*/"# export SLURM_MEM_PER_CPU"/g  ${CaseName}.*.run
  #sed -i s/"# Run the model".*/"unset SLURM_MEM_PER_NODEi; unset SLURM_MEM_PER_GPU"/g  ${CaseName}.*.run
  old_namelist=$(< ${SupportData}/ToBeReplaced_atm_namelist_${model_type} )
  new_namelist=$(< ${SupportData}/ToBeUpdated_atm_namelist_${model_type} )
  current_namelist=$(< Buildconf/cam.buildnml.csh )
  echo "${current_namelist/${old_namelist}/${new_namelist}}" > Buildconf/cam.buildnml.csh
  sedStr=`echo "met_data_file = \'${SP_Prefix}_${yy}${mm}${dd}_${ss}.nc\'"  | sed 's/\//\\\\\//g' `
  sed -i s/"met_data_file".*/"${sedStr}"/g  Buildconf/cam.buildnml.csh
  sedStr=`echo met_data_path = \'${BCK_dataDir}\' | sed 's/\//\\\\\//g' `
  sed -i s/"met_data_path".*/"${sedStr}"/g  Buildconf/cam.buildnml.csh
  sedStr=`echo met_filenames_list = \'${BCK_dataDir}/../${MetDataList}\' | sed 's/\//\\\\\//g' `
  sed -i s/"met_filenames_list".*/"${sedStr}"/g  Buildconf/cam.buildnml.csh
  sed -i s/"met_max_rlx =".*/"met_max_rlx = ${met_rlx}"/g  Buildconf/cam.buildnml.csh

  if [ "${model_type}" == "AMIP" ]; then
    [ "${HPC}" == "fram" ] && sedStr=`echo "set dat_datpath = /cluster/projects/nn9385k/CMIP6_forcing/AMIP" | sed 's/\//\\\\\//g' `
    [ "${HPC}" == "betzy" ] && sedStr=`echo "set dat_datpath = /cluster/projects/nn9385k/people/earnest/AMIP" | sed 's/\//\\\\\//g' `
    sed -i s/"set dat_datpath".*/"${sedStr}"/g Buildconf/docn.buildnml.csh
    sed -i s/"set dat_datfile".*/"set dat_datfile = sst_HadOIBl_bc_1.9x2.5_1850_2008_c100127.nc"/g Buildconf/docn.buildnml.csh
    sed -i s/"set year_align".*/"set year_align = 1850"/g Buildconf/docn.buildnml.csh
    sed -i s/"set year_start".*/"set year_start = 1850"/g Buildconf/docn.buildnml.csh
    sed -i s/"set year_end".*/"set year_end = 2008"/g Buildconf/docn.buildnml.csh
    [ "${HPC}" == "fram" ] && sedStr=`echo "/cluster/projects/nn9385k/CMIP6_forcing/AMIP/sst_HadOIBl_bc_1.9x2.5_clim_c061031_p05.nc" | sed 's/\//\\\\\//g' `
    [ "${HPC}" == "betzy" ] && sedStr=`echo "/cluster/projects/nn9385k/people/earnest/AMIP/sst_HadOIBl_bc_1.9x2.5_1850_2008_c100127.nc" | sed 's/\//\\\\\//g' `
    sed -i s/"stream_domfilename".*/"stream_domfilename = \'${sedStr}\'"/g Buildconf/cice.buildnml.csh
    sed -i s/"stream_fldfilename".*/"stream_fldfilename = \'${sedStr}\'"/g Buildconf/cice.buildnml.csh
    sed -i s/"stream_year_first".*/"stream_year_first = 1850"/g Buildconf/cice.buildnml.csh
    sed -i s/"stream_year_last".*/"stream_year_last = 2008"/g Buildconf/cice.buildnml.csh
  fi

  cp -f ${SupportData}/SourceMods/src.cam/* ./SourceMods/src.cam/
  cd ./SourceMods/src.cam/
  gzip -d *
  cd ../../
  if [ "${HPC}" == "hexagon" ]; then
    sed -i s/"module load craype\/2.4.2"/"module swap craype craype\/2.4.2"/g env_mach_specific
    echo "setenv MPICH_NO_BUFFER_ALIAS_CHECK 1" >> env_mach_specific
  fi
  #cleanbuildscript=`ls ${CaseName}*.clean_build `
  #${cleanbuildscript}
  buildscript=`ls ${CaseName}*.build`
 # ./${buildscript}
  mkdir -p ${Model_work_dir}/../logs/bld
  mkdir -p ${Model_work_dir}/../run

fi


