#! /bin/bash
set +x
func_setenvxmlValue()
{
if [ ! -f ${scripthome}/${envConfigFilePath}/${EnvCongFile} ]; then
  echo "Missing env configuration file."
  exit 1
fi
node=$1
name=$2
value=$3

xmllint --shell ${scripthome}/${envConfigFilePath}/${EnvCongFile} << EOFxml
cd ${node}[@name="${name}"]/@value
set ${value}
save
EOFxml
#evalStr=`echo "cd ${node}[@name=\"${name}\"]/@value \nset ${value}\nsave" | xmllint --shell ${scripthome}/${envConfigFilePath}/${EnvCongFile} `
#eval ${evalStr}
}
. ${fhome}/func_debug_Setting_${DebugLev}
